// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.35;

/// @title Minimal POLend leveraged-genesis surface consumed by OutrunRouter.
/// @notice Read/write subset of the Memeverse POLend used by the router's PSM-gate leveraged
///      genesis entry: pay real-uAsset interest and credit the borrowed debt to `user`.
interface IPOLendGenesis {
    /// @notice Opens or adds to a leveraged-genesis position: pulls `interestAmount` uAsset from
    ///      the caller (the router) and records the debt against `user`.
    /// @param verseId Launcher-side verse identifier.
    /// @param interestAmount uAsset interest paid, taken from the caller.
    /// @param user Address credited with the borrowed debt.
    /// @return borrowedAmount uAsset-denominated debt generated by this interest payment.
    function leveragedGenesis(uint256 verseId, uint256 interestAmount, address user)
        external
        returns (uint256 borrowedAmount);

    /// @notice Returns the verse uAsset a market is bound to; address(0) when unregistered.
    /// @param verseId Launcher-side verse identifier.
    /// @return uAsset Address of the market's bound uAsset.
    function marketUAsset(uint256 verseId) external view returns (address);
}
